#!/bin/bash
###
#
# cmd: ./xcudnn ~/usr/cuda /usr/local/cuda-8.0/
#
cudnn=$1
cuda=$2
#if [ $cudnn eq "" ] then
#   exit(1)
#fi
echo "copy include."
sudo cp $cudnn/include/cudnn.h $cuda/include/
echo "copy lib64."
sudo rm $cuda/lib64/libcudnn.so
sudo cp $cudnn/lib64/* $cuda/lib64/
sudo ldconfig


